In [1]:
# Import PyTorch
import torch

In [2]:
# Creating Tensors
# Tensors can be scalar, vector, matrix, or multidimensional array.
# We use `torch.tensor` to create tensors.

In [3]:
# Create a scalar tensor
scalar_tensor = torch.tensor(34)
print(scalar_tensor)

tensor(34)


In [4]:
# Create a tensor from a list
L1 = [1, 2, 3, 4, 5]
tensor1 = torch.tensor(L1)
print(tensor1)


tensor([1, 2, 3, 4, 5])


In [5]:
# To print values of this tensor, you will need to iterate
for i in tensor1:
    print(i.item())

1
2
3
4
5


In [6]:
# Check the datatype
print(tensor1.dtype)

torch.int64


In [7]:
# Print each element of tensor_from_list
print("Elements in tensor_from_list:")
for value in tensor1:
    print(value.item())

Elements in tensor_from_list:
1
2
3
4
5


In [8]:
# Check the shape
print(tensor1.shape)

torch.Size([5])


In [9]:
# Create tensor from NumPy array
import numpy as np
numpy_array = np.array([20, 30, 40])
tensor_numpy = torch.tensor(numpy_array)
print(tensor_numpy)

tensor([20, 30, 40], dtype=torch.int32)


In [10]:
# Matrix tensor
l1 = [1, 2, 3]
l2 = [4, 5, 6]
plist = [l1, l2]
matrix_tensor = torch.tensor(plist)
print("plist", plist)
print("matrix tensor: ", matrix_tensor)

plist [[1, 2, 3], [4, 5, 6]]
matrix tensor:  tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
# 3D tensors
l3 = [7, 8, 9]
l4 = [10, 11, 12]
plist2 = [l3, l4]
three_d_tensor = torch.tensor([plist, plist2])
print(three_d_tensor)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [12]:
# Create an empty 1D tensor of size 5
empty_tensor_1d = torch.empty(5)
print("Empty 1D tensor:", empty_tensor_1d)

Empty 1D tensor: tensor([8.5763e+14, 1.4854e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00])


In [13]:
# Create an empty 2D tensor of size (3, 3)
empty_tensor_2d = torch.empty(3, 3)
print("Empty 2D tensor:", empty_tensor_2d)

Empty 2D tensor: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [14]:
# Create a tensor of zeros with size 3
zeros_tensor_1d = torch.zeros(3)
print("1D tensor of zeros:", zeros_tensor_1d)

1D tensor of zeros: tensor([0., 0., 0.])


In [15]:
# Create a 2D tensor of zeros with size (2, 4)
zeros_tensor_2d = torch.zeros(2, 4)
print("2D tensor of zeros:", zeros_tensor_2d)

2D tensor of zeros: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [16]:
# Create a 1D tensor of ones with size 4
ones_tensor_1d = torch.ones(4)
print("1D tensor of ones:", ones_tensor_1d)

1D tensor of ones: tensor([1., 1., 1., 1.])


In [17]:
# Create a 2D tensor of ones with size (2, 3)
ones_tensor_2d = torch.ones(2, 3)
print("2D tensor of ones:", ones_tensor_2d)

2D tensor of ones: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [18]:
# Create a 1D tensor filled with the value 7
full_tensor_1d = torch.full((5,), 7)
print("1D tensor filled with 7:", full_tensor_1d)

1D tensor filled with 7: tensor([7, 7, 7, 7, 7])


In [19]:
# Create a 2D tensor of size (2, 3) filled with the value 10
full_tensor_2d = torch.full((2, 3), 10)
print("2D tensor filled with 10:", full_tensor_2d)

2D tensor filled with 10: tensor([[10, 10, 10],
        [10, 10, 10]])


In [20]:
# Create a tensor with values from 0 to 10 with a step of 2
arange_tensor_1 = torch.arange(0, 10, 2)
print("Tensor with values from 0 to 10 with step 2:", arange_tensor_1)

Tensor with values from 0 to 10 with step 2: tensor([0, 2, 4, 6, 8])


In [21]:
# Create a tensor with values from 5 to 20 with a step of 3
arange_tensor_2 = torch.arange(5, 20, 3)
print("Tensor with values from 5 to 20 with step 3:", arange_tensor_2)

Tensor with values from 5 to 20 with step 3: tensor([ 5,  8, 11, 14, 17])


In [22]:
# Create a tensor with 5 evenly spaced values between 0 and 1
linspace_tensor_1 = torch.linspace(0, 1, 5)
print("Tensor with 5 evenly spaced values between 0 and 1:", linspace_tensor_1)

Tensor with 5 evenly spaced values between 0 and 1: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [23]:
# Create a tensor with 10 evenly spaced values between -3 and 3
linspace_tensor_2 = torch.linspace(-3, 3, 10)
print("Tensor with 10 evenly spaced values between -3 and 3:", linspace_tensor_2)

Tensor with 10 evenly spaced values between -3 and 3: tensor([-3.0000, -2.3333, -1.6667, -1.0000, -0.3333,  0.3333,  1.0000,  1.6667,
         2.3333,  3.0000])


In [24]:
# Create a 2x2 identity matrix
eye_tensor_1 = torch.eye(2)
print("2x2 Identity matrix:", eye_tensor_1)

2x2 Identity matrix: tensor([[1., 0.],
        [0., 1.]])


In [25]:
# Create a 4x4 identity matrix
eye_tensor_2 = torch.eye(4)
print("4x4 Identity matrix:", eye_tensor_2)

4x4 Identity matrix: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [26]:
# Create a 3x3 random tensor with values between 0 and 1
random_tensor_uniform = torch.rand(3, 3)
print(random_tensor_uniform)

tensor([[0.3539, 0.7182, 0.9315],
        [0.0213, 0.9309, 0.8041],
        [0.7268, 0.8092, 0.1959]])


In [27]:
# Create a 4x2 random tensor from a normal distribution
random_tensor_normal = torch.randn(4, 2)
print(random_tensor_normal)

tensor([[ 0.3710, -2.8737],
        [-0.8449, -1.6101],
        [ 0.1853,  0.1512],
        [-1.2192, -1.5168]])


In [28]:
# Create a 2x3 random tensor with integers between 0 and 10
random_tensor_integers = torch.randint(0, 10, (2, 3))
print(random_tensor_integers)

tensor([[5, 0, 4],
        [6, 4, 5]])


In [29]:
# Set seed for reproducibility
torch.manual_seed(42)

# Create a random tensor
random_tensor_seeded = torch.rand(2, 2)
print(random_tensor_seeded)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])


In [30]:
# Create a random tensor with values between 5 and 10
random_tensor_range = 5 + (torch.rand(3, 3) * (10 - 5))
print(random_tensor_range)

tensor([[6.9522, 8.0045, 6.2829],
        [8.9682, 9.7039, 5.6659],
        [9.6730, 7.9679, 9.3470]])


## Exercises

1. Create a tensor filled with zeroes of size 5x3. Print the tensor and its type.

In [31]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


2. Create a tensor of size 5x3 of datatype int16

In [33]:
i = torch.ones((5,3), dtype = torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


Use torch.manual_seed(seed_value) to set the random seed and then create a 2x2 tensor of random values between 0 and 1. 

In [34]:
torch.manual_seed(1729)

In [39]:
r1= torch.rand(2,2)
print(r1)

tensor([[0.1366, 0.1025],
        [0.1841, 0.7264]])


change seed value to 123 and regenerate tensor

In [40]:
torch.manual_seed(123)
r2= torch.rand(2,2)
print(r2)

tensor([[0.2961, 0.5166],
        [0.2517, 0.6886]])


now change the seed back to original value and see what happens

In [42]:
torch.manual_seed(1729)
r1= torch.rand(2,2)
print(r1)torch.manual_seed(1729)

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


reseeding generates the same sequence. 

In [43]:
torch.manual_seed(1729)
r1= torch.rand(2,2)
print(r1)

tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
