#Advanced Neural Networks: Deep Learning for Sequential Analysis - Assignment 1: Tensors

#Rhichard Koh

# Assignment 1: PyTorch Tensors


### Instructions:
- This assignment is worth **15%** of your final grade.
- Complete all exercises in this notebook.
- Submit your completed notebook by the due date.
- Ensure you use proper comments and explanations in your code.

### Learning Objectives:
- Understand and apply tensor operations in PyTorch.
- Perform data manipulation and transformation using tensors.
- Implement advanced tensor operations like broadcasting and automatic differentiation.



### Question 1: Tensor Creation (10 points)
1. Create the following tensors:
   - A 3x3 tensor filled with random values uniformly distributed between 0 and 1.
   - A 4x4 tensor filled with zeros, then modify its diagonal elements to have the value 1.
   - A 1-dimensional tensor with values ranging from -5 to 5 with a step size of 0.5.
2. Print each tensor and its shape.

**Note:** Use appropriate PyTorch functions to create these tensors.


In [1]:
import torch

# 1. A 3x3 tensor filled with random values uniformly distributed between 0 and 1.
tensor_random = torch.rand(3, 3) # Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)

In [2]:
# 2. A 4x4 tensor filled with zeros, then modify its diagonal elements to have the value 1.
tensor_identity = torch.zeros(4, 4) # Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size (4x4).
tensor_identity = tensor_identity.fill_diagonal_(1) # Fills the diagonal with a scalar value of 1.

In [3]:
# 3. A 1-dimensional tensor with values ranging from -5 to 5 with a step size of 0.5.
tensor_range = torch.arange(-5, 5, 0.5) # Returns a 1-D tensor of size ⌈ end − start / step ⌉ with values from the interval [start, end) taken with common difference step beginning from start.

## Print each tensor and its shape.

In [4]:
print("Random Tensor:")
print(tensor_random)
print("Shape:", tensor_random.shape)

Random Tensor:
tensor([[0.4437, 0.4415, 0.1353],
        [0.3970, 0.9612, 0.3035],
        [0.1089, 0.5916, 0.6068]])
Shape: torch.Size([3, 3])


In [5]:
print("Identity Tensor:")
print(tensor_identity)
print("Shape:", tensor_identity.shape)

Identity Tensor:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Shape: torch.Size([4, 4])


In [6]:
print("Range Tensor:")
print(tensor_range)
print("Shape:", tensor_range.shape)

Range Tensor:
tensor([-5.0000, -4.5000, -4.0000, -3.5000, -3.0000, -2.5000, -2.0000, -1.5000,
        -1.0000, -0.5000,  0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,
         3.0000,  3.5000,  4.0000,  4.5000])
Shape: torch.Size([20])



### Question 2: Basic Tensor Operations (20 points)
1. Create two 2x3 tensors with random integers between 1 and 10.
2. Perform the following operations on these tensors:
   - Element-wise addition
   - Element-wise multiplication
   - Matrix multiplication (ensure tensors are of compatible shape)
   - Calculate the mean and standard deviation of the resulting tensor from matrix multiplication.
3. Print the results of each operation with appropriate labels.

**Hint:** Use `torch.matmul` for matrix multiplication.


In [7]:
first_tensor = torch.randint(1, 11, (2, 3)) # Returns a tensor filled with random numbers from a uniform distribution on the interval [1,10)
second_tensor = torch.randint(1, 11, (2, 3)) # Returns a tensor filled with random numbers from a uniform distribution on the interval [1,10)

In [8]:
print("1st Tensor:")
print(first_tensor)
print("Shape:", first_tensor.shape)

1st Tensor:
tensor([[ 8, 10, 10],
        [ 7,  3,  1]])
Shape: torch.Size([2, 3])


In [9]:
print("2nd Tensor:")
print(second_tensor)
print("Shape:", second_tensor.shape)

2nd Tensor:
tensor([[4, 4, 9],
        [1, 7, 3]])
Shape: torch.Size([2, 3])


## Element Wise Addition

In [10]:
element_wise_addition = first_tensor + second_tensor # adds the two tensors element wise.
print("Element-wise Addition:")
print(element_wise_addition)
print("Shape:", element_wise_addition.shape)

Element-wise Addition:
tensor([[12, 14, 19],
        [ 8, 10,  4]])
Shape: torch.Size([2, 3])


## Element Wise Multiplication

In [11]:
element_wise_multiplication = first_tensor * second_tensor # multiplies the two tensors element wise.
print("Element-wise Multiplication:")
print(element_wise_multiplication)
print("Shape:", element_wise_multiplication.shape)

Element-wise Multiplication:
tensor([[32, 40, 90],
        [ 7, 21,  3]])
Shape: torch.Size([2, 3])


## Matrix Multiplication

In [12]:
print("Shape:", first_tensor.shape) # Checking if we need to Transpose for Matrix Multiplication.
print("Shape:", second_tensor.shape) # Checking if we need to Transpose for Matrix Multiplication.
print("--------------------------------------------------------------------------------------")
matrix_multiplication = torch.matmul(first_tensor, second_tensor.T) # Returns the matrix product of two tensors. We also needed to transpose one of the tensors.
print("Transposed Shape: ", second_tensor.T.shape)
print("--------------------------------------------------------------------------------------")
print("Matrix Multiplication:")
print(matrix_multiplication)
print("Shape:", matrix_multiplication.shape)

Shape: torch.Size([2, 3])
Shape: torch.Size([2, 3])
--------------------------------------------------------------------------------------
Transposed Shape:  torch.Size([3, 2])
--------------------------------------------------------------------------------------
Matrix Multiplication:
tensor([[162, 108],
        [ 49,  31]])
Shape: torch.Size([2, 2])


## Calculate the mean and standard deviation of the resulting tensor from matrix multiplication.

In [13]:
mean = matrix_multiplication.float().mean() # Calculates the mean of the matrix.
std = matrix_multiplication.float().std() # Calculates the standard deviation of the matrix.
print("Mean:", mean)
print("Standard Deviation:", std)

Mean: tensor(87.5000)
Standard Deviation: tensor(59.5679)


## Print the results of each operation with appropriate labels

In [14]:
print("1st Tensor:")
print(first_tensor)
print("Shape:", first_tensor.shape)
print("======================================================================================")
print("2nd Tensor:")
print(second_tensor)
print("Shape:", second_tensor.shape)
print("======================================================================================")
print("Element-wise Addition:")
print(element_wise_addition)
print("Shape:", element_wise_addition.shape)
print("======================================================================================")
print("Element-wise Multiplication:")
print(element_wise_multiplication)
print("Shape:", element_wise_multiplication.shape)
print("======================================================================================")
print("Shape:", first_tensor.shape) # Checking if we need to Transpose for Matrix Multiplication.
print("Shape:", second_tensor.shape) # Checking if we need to Transpose for Matrix Multiplication.
print("--------------------------------------------------------------------------------------")
matrix_multiplication = torch.matmul(first_tensor, second_tensor.T) # Returns the matrix product of two tensors. We also needed to transpose one of the tensors.
print("Transposed Shape: ", second_tensor.T.shape)
print("--------------------------------------------------------------------------------------")
print("Matrix Multiplication:")
print(matrix_multiplication)
print("Shape:", matrix_multiplication.shape)
print("======================================================================================")
print("Mean:", mean)
print("Standard Deviation:", std)

1st Tensor:
tensor([[ 8, 10, 10],
        [ 7,  3,  1]])
Shape: torch.Size([2, 3])
2nd Tensor:
tensor([[4, 4, 9],
        [1, 7, 3]])
Shape: torch.Size([2, 3])
Element-wise Addition:
tensor([[12, 14, 19],
        [ 8, 10,  4]])
Shape: torch.Size([2, 3])
Element-wise Multiplication:
tensor([[32, 40, 90],
        [ 7, 21,  3]])
Shape: torch.Size([2, 3])
Shape: torch.Size([2, 3])
Shape: torch.Size([2, 3])
--------------------------------------------------------------------------------------
Transposed Shape:  torch.Size([3, 2])
--------------------------------------------------------------------------------------
Matrix Multiplication:
tensor([[162, 108],
        [ 49,  31]])
Shape: torch.Size([2, 2])
Mean: tensor(87.5000)
Standard Deviation: tensor(59.5679)



### Question 3: Tensor Slicing and Indexing (20 points)
1. Create a 5x5 tensor with random values between 0 and 1.
2. Extract the following using tensor slicing:
   - The entire second row.
   - The entire third column.
   - A 3x3 sub-tensor from the top-left corner of the original tensor.
3. Set all elements in the last row to 1.
4. Print the modified tensor and the extracted slices.

**Note:** Ensure the original tensor is modified as required.


## Create a 5x5 tensor with random values between 0 and 1.

In [15]:
fivexfive_tensor = torch.rand(5, 5) # Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
original_tensor = fivexfive_tensor.clone() # Copies the tensor.

In [16]:
print("5x5 Tensor:")
print(fivexfive_tensor)
print("Shape:", fivexfive_tensor.shape)

5x5 Tensor:
tensor([[0.9614, 0.8791, 0.5513, 0.9133, 0.3941],
        [0.8368, 0.7393, 0.3220, 0.7567, 0.2863],
        [0.3266, 0.0885, 0.1252, 0.3797, 0.4632],
        [0.8194, 0.0634, 0.8059, 0.2232, 0.3864],
        [0.8454, 0.9162, 0.4493, 0.2618, 0.6831]])
Shape: torch.Size([5, 5])


## Extract the following using tensor slicing:

*   The entire second row.
*   The entire third column.
*   A 3x3 sub-tensor from the top-left corner of the original tensor.

In [17]:
# The entire second row
second_row = fivexfive_tensor[1, :] # Returns the second row of the tensor.
print("2nd Row:")
print(second_row)
print("Shape:", second_row.shape)

2nd Row:
tensor([0.8368, 0.7393, 0.3220, 0.7567, 0.2863])
Shape: torch.Size([5])


In [18]:
# The entire third column
third_column = fivexfive_tensor[:, 2] # Returns the third column of the tensor.
print("3rd Column:")
print(third_column)
print("Shape:", third_column.shape)

3rd Column:
tensor([0.5513, 0.3220, 0.1252, 0.8059, 0.4493])
Shape: torch.Size([5])


In [19]:
# A 3x3 sub-tensor from the top-left corner of the original tensor
sub_tensor = fivexfive_tensor[:3, :3] # Returns a slice of the tensor targeting the top left of the matrix.
print("Sub-Tensor:")
print(sub_tensor)
print("Shape:", sub_tensor.shape)

Sub-Tensor:
tensor([[0.9614, 0.8791, 0.5513],
        [0.8368, 0.7393, 0.3220],
        [0.3266, 0.0885, 0.1252]])
Shape: torch.Size([3, 3])


## Set all elements in the last row to 1

In [20]:
# Set all elements in the last row to 1
fivexfive_tensor[-1, :] = 1 # Sets the last row of the tensor to 1.
print("Modified Tensor:")
print(fivexfive_tensor)
print("Shape:", fivexfive_tensor.shape)

Modified Tensor:
tensor([[0.9614, 0.8791, 0.5513, 0.9133, 0.3941],
        [0.8368, 0.7393, 0.3220, 0.7567, 0.2863],
        [0.3266, 0.0885, 0.1252, 0.3797, 0.4632],
        [0.8194, 0.0634, 0.8059, 0.2232, 0.3864],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])
Shape: torch.Size([5, 5])


## Print the modified tensor and the extracted slices

In [21]:
print("5x5 Tensor:")
print(original_tensor)
print("Shape:", fivexfive_tensor.shape)
print("======================================================================================")
print("2nd Row:")
print(second_row)
print("Shape:", second_row.shape)
print("======================================================================================")
print("3rd Column:")
print(third_column)
print("Shape:", third_column.shape)
print("======================================================================================")
print("Sub-Tensor:")
print(sub_tensor)
print("Shape:", sub_tensor.shape)
print("======================================================================================")
print("Modified Tensor:")
print(fivexfive_tensor)
print("Shape:", fivexfive_tensor.shape)

5x5 Tensor:
tensor([[0.9614, 0.8791, 0.5513, 0.9133, 0.3941],
        [0.8368, 0.7393, 0.3220, 0.7567, 0.2863],
        [0.3266, 0.0885, 0.1252, 0.3797, 0.4632],
        [0.8194, 0.0634, 0.8059, 0.2232, 0.3864],
        [0.8454, 0.9162, 0.4493, 0.2618, 0.6831]])
Shape: torch.Size([5, 5])
2nd Row:
tensor([0.8368, 0.7393, 0.3220, 0.7567, 0.2863])
Shape: torch.Size([5])
3rd Column:
tensor([0.5513, 0.3220, 0.1252, 0.8059, 1.0000])
Shape: torch.Size([5])
Sub-Tensor:
tensor([[0.9614, 0.8791, 0.5513],
        [0.8368, 0.7393, 0.3220],
        [0.3266, 0.0885, 0.1252]])
Shape: torch.Size([3, 3])
Modified Tensor:
tensor([[0.9614, 0.8791, 0.5513, 0.9133, 0.3941],
        [0.8368, 0.7393, 0.3220, 0.7567, 0.2863],
        [0.3266, 0.0885, 0.1252, 0.3797, 0.4632],
        [0.8194, 0.0634, 0.8059, 0.2232, 0.3864],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])
Shape: torch.Size([5, 5])



### Question 4: Tensor Reshaping and Broadcasting (25 points)
1. Create a tensor of shape (2, 3, 4) with random values.
2. Reshape this tensor into shape (4, 6) and print the result.
3. Create a 1-dimensional tensor of size 6.
4. Use broadcasting to add this tensor to each row of the reshaped tensor.
5. Print the resulting tensor.

**Hint:** Ensure the dimensions are compatible for broadcasting.


## Create a tensor of shape (2, 3, 4) with random values.

In [22]:
tensor234 = torch.rand(2, 3, 4) # Returns a tensor filled with random values with a shape of 2 matricies, 3 rows, and 4 columns
print("(2, 3, 4) Tensor:")
print(tensor234)
print("Shape:", tensor234.shape)

(2, 3, 4) Tensor:
tensor([[[0.3051, 0.7055, 0.3844, 0.9776],
         [0.2469, 0.6749, 0.3267, 0.8816],
         [0.8179, 0.2889, 0.6895, 0.1538]],

        [[0.7160, 0.2582, 0.8285, 0.2327],
         [0.4626, 0.5618, 0.7954, 0.9484],
         [0.2242, 0.9805, 0.0565, 0.2383]]])
Shape: torch.Size([2, 3, 4])


## Reshape this tensor into shape (4, 6) and print the result.

In [23]:
tensor46 = tensor234.reshape(4, 6) # Returns a tensor with the same data and number of elements as the first tensor but reshaped to a 4 row 6 column single matrix.
print("(4, 6) Tensor:")
print(tensor46)
print("Shape:", tensor46.shape)

(4, 6) Tensor:
tensor([[0.3051, 0.7055, 0.3844, 0.9776, 0.2469, 0.6749],
        [0.3267, 0.8816, 0.8179, 0.2889, 0.6895, 0.1538],
        [0.7160, 0.2582, 0.8285, 0.2327, 0.4626, 0.5618],
        [0.7954, 0.9484, 0.2242, 0.9805, 0.0565, 0.2383]])
Shape: torch.Size([4, 6])


## Create a 1-dimensional tensor of size 6.

In [24]:
oned_tensor = torch.rand(6) # Returns a one-dimensional tensor with size 6.
print("1D Tensor:")
print(oned_tensor)
print("Shape:", oned_tensor.shape)

1D Tensor:
tensor([0.6351, 0.3673, 0.8606, 0.8360, 0.8207, 0.3129])
Shape: torch.Size([6])


## Use broadcasting to add this tensor to each row of the reshaped tensor.

Two tensors are “broadcastable” if the following rules hold:

*   Each tensor has at least one dimension.
*   When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

In [25]:
# checking if compatible with broadcasting
print("Shape:", tensor46.shape)
print("Shape:", oned_tensor.shape)
broadcasted_tensor = tensor46 + oned_tensor # Adds the two tensors element wise.

Shape: torch.Size([4, 6])
Shape: torch.Size([6])


## Print the resulting tensor.

In [26]:
print("Broadcasted Tensor:")
print(broadcasted_tensor)
print("Shape:", broadcasted_tensor.shape)

Broadcasted Tensor:
tensor([[0.9402, 1.0728, 1.2449, 1.8136, 1.0677, 0.9877],
        [0.9618, 1.2489, 1.6784, 1.1249, 1.5102, 0.4666],
        [1.3511, 0.6255, 1.6891, 1.0688, 1.2833, 0.8746],
        [1.4305, 1.3157, 1.0847, 1.8166, 0.8772, 0.5512]])
Shape: torch.Size([4, 6])



### Question 5: Autograd and Gradients (25 points)
1. Create a 2x2 tensor with random values and set `requires_grad=True` to track computations.
2. Perform the following operations on this tensor:
   - Multiply the tensor by 3.
   - Calculate the mean of the resulting tensor.
3. Compute the gradient of the mean with respect to the original tensor.
4. Print the resulting gradients.

**Hint:** Use `backward()` to compute the gradients.


## Create a 2x2 tensor with random values and set requires_grad=True to track computations.

In [27]:
twoxtwo_tensor = torch.rand(2, 2, requires_grad=True) # Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1) with requires grad set to true. To allow us to compute the gradients.

Perform the following operations on this tensor:
* Multiply the tensor by 3.
* Calculate the mean of the resulting tensor.


In [28]:
# Multiply the tensor by 3
multiplied_tensor = twoxtwo_tensor * 3
print("Multiplied Tensor:")
print(multiplied_tensor)
print("Shape:", multiplied_tensor.shape)

Multiplied Tensor:
tensor([[1.3734, 1.2821],
        [2.6419, 1.5073]], grad_fn=<MulBackward0>)
Shape: torch.Size([2, 2])


In [29]:
# Calculate the mean of the resulting tensor
mean = multiplied_tensor.float().mean()
print("Mean: ", mean)

Mean:  tensor(1.7012, grad_fn=<MeanBackward0>)


## Compute the gradient of the mean with respect to the original tensor.

In [30]:
mean.backward() # Computes the gradient of the tensor.

## Print the resulting gradients.

In [31]:
gradients = twoxtwo_tensor.grad # Returns the gradient of the tensor.
print("Gradients:")
print(gradients)
print("Shape:", gradients.shape)

Gradients:
tensor([[0.7500, 0.7500],
        [0.7500, 0.7500]])
Shape: torch.Size([2, 2])



### Submission Instructions
- Complete all the tasks in this notebook.
- Ensure all outputs are correctly displayed before submission.
- Save your notebook and submit it through the course's learning management system by the due date.
- Late submissions may incur penalties as per the course policy.

### Grading Criteria:
- Correctness of tensor operations (60%)
- Code readability and comments (20%)
- Completeness of all tasks (20%)
